INSERT INTO Item (category_id, item_name, item_description, item_price, item_stock_quantity) VALUES
(1, 'Mint Leaves', 'Fresh mint leaves for cocktails.', 0.99, 100),
(1, 'Lime', 'Juicy limes for cocktails and drinks.', 0.50, 200),
(2, 'Tequila', 'High-quality tequila for margaritas.', 25.00, 50),
(2, 'Rum', 'Smooth rum for tropical drinks.', 20.00, 60),
(3, 'Vodka', 'Premium vodka for mixed drinks.', 30.00, 40),
(3, 'Tomato Juice', 'Rich tomato juice for Bloody Mary.', 2.00, 80),
(4, 'Pineapple Juice', 'Fresh pineapple juice for cocktails.', 2.50, 100),
(4, 'Coconut Cream', 'Creamy coconut for tropical drinks.', 3.00, 50),
(5, 'Grenadine', 'Sweet syrup for cocktails and drinks.', 1.50, 75),
(5, 'Orange Juice', 'Freshly squeezed orange juice.', 2.00, 100),
(6, 'Simple Syrup', 'Sweet syrup made from sugar and water.', 1.00, 90),
(6, 'Angostura Bitters', 'Aromatic bitters for cocktails.', 8.00, 40),
(7, 'Club Soda', 'Carbonated water for mixing.', 1.00, 120),
(7, 'Sparkling Water', 'Sparkling mineral water for drinks.', 1.50, 80),
(8, 'Coffee Beans', 'Freshly roasted coffee beans for drinks.', 5.00, 30),
(8, 'Cream', 'Fresh cream for coffee drinks.', 2.50, 60),
(9, 'Sugar', 'Granulated sugar for sweetening drinks.', 0.50, 200),
(9, 'Ice Cubes', 'Freshly made ice cubes for drinks.', 0.10, 300),
(10, 'Herbal Tea', 'Assorted herbal tea for refreshing drinks.', 2.00, 70);
