INSERT INTO Drink (drink_name, drink_description, drink_price) VALUES
('Mojito', 'A refreshing cocktail made with mint, lime, sugar, rum, and soda water.', 7.99),
('Pina Colada', 'A tropical drink made with rum, coconut cream, and pineapple juice.', 8.49),
('Margarita', 'A classic cocktail made with tequila, lime juice, and orange liqueur.', 6.99),
('Bloody Mary', 'A savory cocktail made with vodka, tomato juice, and various spices.', 7.49),
('Moscow Mule', 'A cocktail made with vodka, ginger beer, and lime juice.', 6.49),
('Mai Tai', 'A fruity cocktail made with rum, lime juice, and almond syrup.', 7.99),
('Tequila Sunrise', 'A cocktail made with tequila, orange juice, and grenadine.', 6.99),
('Bellini', 'A sparkling cocktail made with Prosecco and peach purée.', 8.49),
('Virgin Mojito', 'A non-alcoholic version of the mojito, made with mint, lime, sugar, and soda water.', 5.99),
('Iced Coffee', 'Chilled coffee served with cream and sugar.', 3.99),
('Lemon Basil Spritzer', 'A refreshing drink made with lemon juice, basil, and sparkling water.', 4.99),
('Fruit Punch', 'A refreshing blend of various fruit juices.', 3.49),
('Cappuccino', 'Espresso mixed with steamed milk and topped with milk foam.', 4.99),
('Hot Chocolate', 'A rich, creamy hot chocolate topped with whipped cream.', 3.99),
('Sparkling Lemonade', 'A fizzy drink made with lemon juice, sugar, and sparkling water.', 2.99),
('Herbal Tea', 'A warm infusion made from various herbs.', 2.49),
('Frozen Daiquiri', 'A blended drink made with rum, lime juice, and sugar.', 8.99),
('Irish Coffee', 'Hot coffee with Irish whiskey and cream.', 5.99),
('Coconut Water', 'Refreshing coconut water served chilled.', 2.49),
('Lemonade', 'A sweet and tangy drink made with lemon juice, sugar, and water.', 2.99);
